In [1]:
!pip install nxviz=='0.6.3'

     |████████████████████████████████| 11.3 MB 8.3 MB/s 
     |████████████████████████████████| 11.2 MB 39.7 MB/s 
     |████████████████████████████████| 884 kB 45.9 MB/s 
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.4 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


In [117]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import nxviz as nv
import seaborn as sns
import pandas as pd
from nxviz import CircosPlot 

Importação arquivo com os aeropostos

In [103]:
airports = pd.read_csv('/content/drive/MyDrive/Cursos/BTI/13 Semestre/Analise de Redes/trabalhos/airports.csv')

Importação arquivo com os vous

In [104]:
flights = pd.read_csv('/content/drive/MyDrive/Cursos/BTI/13 Semestre/Analise de Redes/trabalhos/anac.zip')

In [85]:
G = nx.Graph()

In [86]:
lista = []

Gera uma lista dos aeroportos Brasileiros

In [105]:
for index, row in airports.iterrows():
    if row['country'] == 'BRASIL':
        G.add_node(row['code'],
                   region=row['region'],
                   name=row['name']
                  )
        lista.append(row['code']) 

In [106]:
print(G.nodes)

['SBCF', 'SBGL', 'SBGR', 'SSUM', 'SNBG', 'SSBG', 'SBCV', 'SBLP', 'SBSV', 'SNGI', 'SNTF', 'SBAR', 'SBMO', 'SBPL', 'SNBR', 'SNVR', 'SBKP', 'SBBV', 'SBFL', 'SBPA', '1AON', 'SBAA', 'SBAS', 'SBAU', 'SBBE', 'SBBH', 'SBBR', 'SBCG', 'SBCH', 'SBCJ', 'SBCT', 'SBCY', 'SBDN', 'SBEG', 'SBFC', 'SBFZ', 'SBGO', 'SBIL', 'SBIZ', 'SBJP', 'SBJV', 'SBLO', 'SBMA', 'SBMC', 'SBMQ', 'SBNF', 'SBNT', 'SBPJ', 'SBPN', 'SBPS', 'SBPV', 'SBRF', 'SBRJ', 'SBRP', 'SBSJ', 'SBSL', 'SBSM', 'SBSP', 'SBSR', 'SBTC', 'SBTE', 'SBTU', 'SBUG', 'SBUL', 'SBUR', 'SBVG', 'SBVH', 'SBVT', 'SDAG', 'SNDC', 'SNDM', 'SNTO', 'SSCK', 'SSEP', 'SSER', 'SSHZ', 'SSLT', 'SSPB', 'SSUW', 'SSZR', 'SWFX', 'SWGI', 'SWJI', 'SWKK', 'SWKN', 'SWNQ', 'SWPQ', 'SBBI', 'SBCX', 'SBFI', 'SBSN', 'SDAN', 'SDCO', 'SDUB', 'SNFE', 'SWGN', 'SBCA', 'SBCM', 'SBCR', 'SBME', 'SBML', 'SBPK', 'SBAQ', 'SDVG', 'SBBT', 'SNRU', 'SBMN', 'SBBU', 'SBMG', 'SSTD', 'SBTD', 'SBRG', 'SNOX', 'SNTI', 'SBHT', 'SBIH', 'SBMD', 'SBFN', 'SBIP', 'SBJF', 'SBKG', 'SBMK', 'SBPB', 'SBQV', 'SBTB',

Adiciona as arestas

In [107]:
for index, row in flights.iterrows():

  if row['origin_airport_abbreviation'] == row['destination_airport_abbreviation']:
        continue
  try:
    fo = lista.index(row['origin_airport_abbreviation'])
    fd = lista.index(row['origin_airport_abbreviation'])
  except:
    fo = -1
    fd = -1
  
  if (fo > -1) and (fd > -1 ):
    G.add_edge(row['origin_airport_abbreviation'], row['destination_airport_abbreviation'])

In [108]:
G.edges()

EdgeView([('SBCF', 'KMIA'), ('SBCF', 'SBGL'), ('SBCF', 'SBCT'), ('SBCF', 'SBDN'), ('SBCF', 'SBFL'), ('SBCF', 'SBFZ'), ('SBCF', 'SBGO'), ('SBCF', 'SBGR'), ('SBCF', 'SBJV'), ('SBCF', 'SBKP'), ('SBCF', 'SBLO'), ('SBCF', 'SBMO'), ('SBCF', 'SBNT'), ('SBCF', 'SBPA'), ('SBCF', 'SBPS'), ('SBCF', 'SBRF'), ('SBCF', 'SBRJ'), ('SBCF', 'SBSP'), ('SBCF', 'SBSR'), ('SBCF', 'SBSV'), ('SBCF', 'SBSJ'), ('SBCF', 'SBUL'), ('SBCF', 'SBBR'), ('SBCF', 'SBBH'), ('SBCF', 'SBNF'), ('SBCF', 'SBML'), ('SBCF', 'SBRP'), ('SBCF', 'SBAS'), ('SBCF', 'SBFC'), ('SBCF', 'SBIP'), ('SBCF', 'SBMK'), ('SBCF', 'SBQV'), ('SBCF', 'SBVT'), ('SBCF', 'SBJF'), ('SBCF', 'SBUR'), ('SBCF', 'SBIL'), ('SBCF', 'SBSL'), ('SBCF', 'SBCX'), ('SBCF', 'SBAU'), ('SBCF', 'SBFI'), ('SBCF', 'LPPT'), ('SBCF', 'SAAR'), ('SBCF', 'SACO'), ('SBCF', 'SAEZ'), ('SBCF', 'SBEG'), ('SBCF', 'SBBE'), ('SBCF', 'SBCJ'), ('SBCF', 'SBAR'), ('SBCF', 'SBJP'), ('SBCF', 'SBMQ'), ('SBCF', 'SBCY'), ('SBCF', 'SBPV'), ('SBCF', 'SBTE'), ('SBCF', 'LIRF'), ('SBCF', 'LIMC'), 

In [109]:
print("A rede possue {} nós e {} arestas".format(G.number_of_nodes(),
                                                     G.number_of_edges()))

A rede possue 928 nós e 6295 arestas


In [110]:
G.nodes(data=True)

NodeDataView({'SBCF': {'region': 'SUDESTE', 'name': 'CONFINS'}, 'SBGL': {'region': 'SUDESTE', 'name': 'RIO DE JANEIRO'}, 'SBGR': {'region': 'SUDESTE', 'name': 'GUARULHOS'}, 'SSUM': {'region': 'SUL', 'name': 'UMUARAMA'}, 'SNBG': {'region': 'SUDESTE', 'name': 'BAIXO GUANDU'}, 'SSBG': {'region': 'SUL', 'name': 'BENTO GONÇALVES'}, 'SBCV': {'region': 'NORDESTE', 'name': 'CARAVELAS'}, 'SBLP': {'region': 'NORDESTE', 'name': 'BOM JESUS DA LAPA'}, 'SBSV': {'region': 'NORDESTE', 'name': 'SALVADOR'}, 'SNGI': {'region': 'NORDESTE', 'name': 'GUANAMBI'}, 'SNTF': {'region': 'NORDESTE', 'name': 'TEIXEIRA DE FREITAS'}, 'SBAR': {'region': 'NORDESTE', 'name': 'ARACAJU'}, 'SBMO': {'region': 'NORDESTE', 'name': 'RIO LARGO'}, 'SBPL': {'region': 'NORDESTE', 'name': 'PETROLINA'}, 'SNBR': {'region': 'NORDESTE', 'name': 'BARREIRAS'}, 'SNVR': {'region': 'NORDESTE', 'name': 'VERA CRUZ'}, 'SBKP': {'region': 'SUDESTE', 'name': 'CAMPINAS'}, 'SBBV': {'region': 'NORTE', 'name': 'BOA VISTA'}, 'SBFL': {'region': 'SUL', 

In [94]:
G.edges(data=True)

EdgeDataView([('SBCF', 'KMIA', {}), ('SBCF', 'SBGL', {}), ('SBCF', 'SBCT', {}), ('SBCF', 'SBDN', {}), ('SBCF', 'SBFL', {}), ('SBCF', 'SBFZ', {}), ('SBCF', 'SBGO', {}), ('SBCF', 'SBGR', {}), ('SBCF', 'SBJV', {}), ('SBCF', 'SBKP', {}), ('SBCF', 'SBLO', {}), ('SBCF', 'SBMO', {}), ('SBCF', 'SBNT', {}), ('SBCF', 'SBPA', {}), ('SBCF', 'SBPS', {}), ('SBCF', 'SBRF', {}), ('SBCF', 'SBRJ', {}), ('SBCF', 'SBSP', {}), ('SBCF', 'SBSR', {}), ('SBCF', 'SBSV', {}), ('SBCF', 'SBSJ', {}), ('SBCF', 'SBUL', {}), ('SBCF', 'SBBR', {}), ('SBCF', 'SBBH', {}), ('SBCF', 'SBNF', {}), ('SBCF', 'SBML', {}), ('SBCF', 'SBRP', {}), ('SBCF', 'SBAS', {}), ('SBCF', 'SBFC', {}), ('SBCF', 'SBIP', {}), ('SBCF', 'SBMK', {}), ('SBCF', 'SBQV', {}), ('SBCF', 'SBVT', {}), ('SBCF', 'SBJF', {}), ('SBCF', 'SBUR', {}), ('SBCF', 'SBIL', {}), ('SBCF', 'SBSL', {}), ('SBCF', 'SBCX', {}), ('SBCF', 'SBAU', {}), ('SBCF', 'SBFI', {}), ('SBCF', 'LPPT', {}), ('SBCF', 'SAAR', {}), ('SBCF', 'SACO', {}), ('SBCF', 'SAEZ', {}), ('SBCF', 'SBEG', {

In [113]:
G.nodes["SSBG"]

{'name': 'BENTO GONÇALVES', 'region': 'SUL'}

Conexões do aeroporto SSBG - BENTO GONÇALVES

In [111]:
G["SSBG"]

AtlasView({'KDFW': {}, 'SAEZ': {}, 'SBGL': {}, 'MMMX': {}, 'KJFK': {}, 'SUMU': {}, 'SPIM': {}, 'KCLT': {}, 'SKBO': {}, 'SLPS': {}})

Cria o Circos Plot por Região

In [125]:
c = nv.CircosPlot(G,
                  node_color="region",
                  node_grouping="region",
                  node_order="region",
                  group_order="region",
                  group_legend=False,
                  node_labels=False,
                  group_label_position="region",
                  group_label_color=False,figsize=(10,8))

c.draw()

c.sm.colorbar.remove()

plt.savefig("assortativity.png", 
            format="png",
            dpi=400, 
            bbox_inches="tight",
            transparent=True)


plt.show()

KeyError: ignored

In [96]:
G.nodes['SNBR']

{'region': 'NORDESTE'}

Coeficiente por região

In [97]:
nx.attribute_assortativity_coefficient(G,"region")

0.2037378775422979

Matrix de mistura

In [62]:
e = nx.attribute_mixing_matrix(G,'region')
e

array([[0.03653693, 0.01556791, 0.00913423, 0.00857824, 0.02406672,
        0.00746624],
       [0.01556791, 0.09499603, 0.01890389, 0.0050834 , 0.01945989,
        0.01453535],
       [0.00913423, 0.01890389, 0.        , 0.02025417, 0.07132645,
        0.03073868],
       [0.00857824, 0.0050834 , 0.02025417, 0.0482923 , 0.02803813,
        0.00921366],
       [0.02406672, 0.01945989, 0.07132645, 0.02803813, 0.12200159,
        0.03915806],
       [0.00746624, 0.01453535, 0.03073868, 0.00921366, 0.03915806,
        0.05512311]])

Soma de todos os valores da matriz

In [63]:
np.sum(e)

1.0

In [64]:
a = np.sum(e, axis=1)
b = np.sum(e, axis=0)

display(a)
display(b)

array([0.10135028, 0.16854647, 0.15035743, 0.11945989, 0.30405083,
       0.15623511])

array([0.10135028, 0.16854647, 0.15035743, 0.11945989, 0.30405083,
       0.15623511])

In [65]:
tr_e = np.trace(e)
tr_e

0.3569499602859413

Soma da matriz

In [66]:
multi_e = np.sum(np.matmul(e,e))

Métrica de variedade 

In [67]:
r = (tr_e - multi_e)/(1 - multi_e)
r

0.2037378775422979

Verificando se a Métrica de variedade é igual ao coeficiente por região.

In [68]:
assert (r == nx.attribute_assortativity_coefficient(G,"region"))

Grau médio de vizinhos 

In [69]:
degree, avg_neigh_degree = zip(*nx.average_degree_connectivity(G).items())

In [70]:
degree = list(degree)
avg_neigh_degree = list(avg_neigh_degree)

In [124]:
plt.style.use("fivethirtyeight")
fig, ax = plt.subplots(1,1,figsize=(12,8))

sns.regplot(degree,avg_neigh_degree,ax=ax)

ax.set_xlabel("Grau do Nó")
ax.set_ylabel("Grau médio de vizinhos")
ax.set_xlim(0,65)


plt.show()

/usr/local/lib/python3.7/dist-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


ImportError: ignored

<Figure size 864x576 with 1 Axes>

In [72]:
nx.degree_assortativity_coefficient(G)

-0.3925073385320804

Numero de conexões

In [73]:
nx.number_connected_components(G)

2

In [81]:
nx.is_connected(nx.Graph(G))

NetworkXPointlessConcept: ignored

928