In [1]:
!pip install nxviz=='0.6.3'

     |████████████████████████████████| 11.2 MB 5.2 MB/s 
     |████████████████████████████████| 11.3 MB 19.9 MB/s 
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.4 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


In [2]:
import networkx as nx
import matplotlib as plt
import numpy as np
import nxviz as nv
import seaborn as sns
import pandas as pd

Importação arquivo com os aeropostos

In [3]:
airports = pd.read_csv('/content/drive/MyDrive/Cursos/BTI/13 Semestre/Analise de Redes/trabalhos/airports.csv')

Importação arquivo com os vous

In [4]:
flights = pd.read_csv('/content/drive/MyDrive/Cursos/BTI/13 Semestre/Analise de Redes/trabalhos/anac.zip')

In [5]:
G = nx.Graph()

In [7]:
lista = []

Gera uma lista dos aeroportos Brasileiros

In [8]:
for index, row in airports.iterrows():
    if row['country'] == 'BRASIL':
        G.add_node(row['code'],
                region=row['region']
                )
        lista.append(row['code']) 

In [9]:
print(G.nodes)

['SBCF', 'SBGL', 'SBGR', 'SSUM', 'SNBG', 'SSBG', 'SBCV', 'SBLP', 'SBSV', 'SNGI', 'SNTF', 'SBAR', 'SBMO', 'SBPL', 'SNBR', 'SNVR', 'SBKP', 'SBBV', 'SBFL', 'SBPA', '1AON', 'SBAA', 'SBAS', 'SBAU', 'SBBE', 'SBBH', 'SBBR', 'SBCG', 'SBCH', 'SBCJ', 'SBCT', 'SBCY', 'SBDN', 'SBEG', 'SBFC', 'SBFZ', 'SBGO', 'SBIL', 'SBIZ', 'SBJP', 'SBJV', 'SBLO', 'SBMA', 'SBMC', 'SBMQ', 'SBNF', 'SBNT', 'SBPJ', 'SBPN', 'SBPS', 'SBPV', 'SBRF', 'SBRJ', 'SBRP', 'SBSJ', 'SBSL', 'SBSM', 'SBSP', 'SBSR', 'SBTC', 'SBTE', 'SBTU', 'SBUG', 'SBUL', 'SBUR', 'SBVG', 'SBVH', 'SBVT', 'SDAG', 'SNDC', 'SNDM', 'SNTO', 'SSCK', 'SSEP', 'SSER', 'SSHZ', 'SSLT', 'SSPB', 'SSUW', 'SSZR', 'SWFX', 'SWGI', 'SWJI', 'SWKK', 'SWKN', 'SWNQ', 'SWPQ', 'SBBI', 'SBCX', 'SBFI', 'SBSN', 'SDAN', 'SDCO', 'SDUB', 'SNFE', 'SWGN', 'SBCA', 'SBCM', 'SBCR', 'SBME', 'SBML', 'SBPK', 'SBAQ', 'SDVG', 'SBBT', 'SNRU', 'SBMN', 'SBBU', 'SBMG', 'SSTD', 'SBTD', 'SBRG', 'SNOX', 'SNTI', 'SBHT', 'SBIH', 'SBMD', 'SBFN', 'SBIP', 'SBJF', 'SBKG', 'SBMK', 'SBPB', 'SBQV', 'SBTB',

Adiciona as arestas

In [14]:
for index, row in flights.iterrows():

  if row['origin_airport_abbreviation'] == row['destination_airport_abbreviation']:
        continue
  try:
    fo = lista.index(row['origin_airport_abbreviation'])
    fd = lista.index(row['origin_airport_abbreviation'])
  except:
    fo = -1
    fd = -1
  
  if (fo > -1) and (fd > -1 ):
    G.add_edge(row['origin_airport_abbreviation'], row['destination_airport_abbreviation'])

In [15]:
G.edges()

EdgeView([('SBCF', 'KMIA'), ('SBCF', 'SBGL'), ('SBCF', 'SBCT'), ('SBCF', 'SBDN'), ('SBCF', 'SBFL'), ('SBCF', 'SBFZ'), ('SBCF', 'SBGO'), ('SBCF', 'SBGR'), ('SBCF', 'SBJV'), ('SBCF', 'SBKP'), ('SBCF', 'SBLO'), ('SBCF', 'SBMO'), ('SBCF', 'SBNT'), ('SBCF', 'SBPA'), ('SBCF', 'SBPS'), ('SBCF', 'SBRF'), ('SBCF', 'SBRJ'), ('SBCF', 'SBSP'), ('SBCF', 'SBSR'), ('SBCF', 'SBSV'), ('SBCF', 'SBSJ'), ('SBCF', 'SBUL'), ('SBCF', 'SBBR'), ('SBCF', 'SBBH'), ('SBCF', 'SBNF'), ('SBCF', 'SBML'), ('SBCF', 'SBRP'), ('SBCF', 'SBAS'), ('SBCF', 'SBFC'), ('SBCF', 'SBIP'), ('SBCF', 'SBMK'), ('SBCF', 'SBQV'), ('SBCF', 'SBVT'), ('SBCF', 'SBJF'), ('SBCF', 'SBUR'), ('SBCF', 'SBIL'), ('SBCF', 'SBSL'), ('SBCF', 'SBCX'), ('SBCF', 'SBAU'), ('SBCF', 'SBFI'), ('SBCF', 'LPPT'), ('SBCF', 'SAAR'), ('SBCF', 'SACO'), ('SBCF', 'SAEZ'), ('SBCF', 'SBEG'), ('SBCF', 'SBBE'), ('SBCF', 'SBCJ'), ('SBCF', 'SBAR'), ('SBCF', 'SBJP'), ('SBCF', 'SBMQ'), ('SBCF', 'SBCY'), ('SBCF', 'SBPV'), ('SBCF', 'SBTE'), ('SBCF', 'LIRF'), ('SBCF', 'LIMC'), 

In [16]:
print("The network has {} nodes and {} edges".format(G.number_of_nodes(),
                                                     G.number_of_edges()))

The network has 928 nodes and 6295 edges


In [17]:
G.nodes(data=True)

NodeDataView({'SBCF': {'region': 'SUDESTE'}, 'SBGL': {'region': 'SUDESTE'}, 'SBGR': {'region': 'SUDESTE'}, 'SSUM': {'region': 'SUL'}, 'SNBG': {'region': 'SUDESTE'}, 'SSBG': {'region': 'SUL'}, 'SBCV': {'region': 'NORDESTE'}, 'SBLP': {'region': 'NORDESTE'}, 'SBSV': {'region': 'NORDESTE'}, 'SNGI': {'region': 'NORDESTE'}, 'SNTF': {'region': 'NORDESTE'}, 'SBAR': {'region': 'NORDESTE'}, 'SBMO': {'region': 'NORDESTE'}, 'SBPL': {'region': 'NORDESTE'}, 'SNBR': {'region': 'NORDESTE'}, 'SNVR': {'region': 'NORDESTE'}, 'SBKP': {'region': 'SUDESTE'}, 'SBBV': {'region': 'NORTE'}, 'SBFL': {'region': 'SUL'}, 'SBPA': {'region': 'SUL'}, '1AON': {'region': 'NORTE'}, 'SBAA': {'region': 'NORTE'}, 'SBAS': {'region': 'SUDESTE'}, 'SBAU': {'region': 'SUDESTE'}, 'SBBE': {'region': 'NORTE'}, 'SBBH': {'region': 'SUDESTE'}, 'SBBR': {'region': 'CENTRO-OESTE'}, 'SBCG': {'region': 'CENTRO-OESTE'}, 'SBCH': {'region': 'SUL'}, 'SBCJ': {'region': 'NORTE'}, 'SBCT': {'region': 'SUL'}, 'SBCY': {'region': 'CENTRO-OESTE'}, 'SB

Cria o Circos Plot por Região

In [31]:
c = nv.CircosPlot(G,
                  node_color="region",
                  node_grouping="region",
                  node_order="region",
                  group_order="alphabetically",
                  group_legend=False,
                  node_labels=False,
                  group_label_position="middle",
                  group_label_color=False,figsize=(10,8))

c.draw()

c.sm.colorbar.remove()

plt.savefig("assortativity.png", 
            format="png",
            dpi=400, 
            bbox_inches="tight",
            transparent=True)


plt.show()

KeyError: ignored

In [32]:
G.nodes['SNBR']

{'region': 'NORDESTE'}

Coeficiente por região

In [33]:
nx.attribute_assortativity_coefficient(G,"region")

0.2037378775422978

In [34]:
e = nx.attribute_mixing_matrix(G,'region')
e

array([[0.03653693, 0.00857824, 0.02406672, 0.00746624, 0.01556791,
        0.00913423],
       [0.00857824, 0.0482923 , 0.02803813, 0.00921366, 0.0050834 ,
        0.02025417],
       [0.02406672, 0.02803813, 0.12200159, 0.03915806, 0.01945989,
        0.07132645],
       [0.00746624, 0.00921366, 0.03915806, 0.05512311, 0.01453535,
        0.03073868],
       [0.01556791, 0.0050834 , 0.01945989, 0.01453535, 0.09499603,
        0.01890389],
       [0.00913423, 0.02025417, 0.07132645, 0.03073868, 0.01890389,
        0.        ]])

In [35]:
np.sum(e)

1.0

In [36]:
a = np.sum(e, axis=1)
b = np.sum(e, axis=0)

display(a)
display(b)

array([0.10135028, 0.11945989, 0.30405083, 0.15623511, 0.16854647,
       0.15035743])

array([0.10135028, 0.11945989, 0.30405083, 0.15623511, 0.16854647,
       0.15035743])

In [37]:
tr_e = np.trace(e)
tr_e

0.3569499602859412